export const qList = {
    "triste": "sad",
    "mahalang": "sick",
    "cho'cho": "eat" ,
    "kada dia": "everyday" ,
    "eskuela": "school" ,
    "asagua": "wife",
    "nobia": "girlfriend" ,
    "nobiu": "boyfriend" ,
    "bintåna": "window" ,
    "sumåsaga": "live (place)",
    "mafañagu": "born",
    "faisen": "ask",
    "gi": "at",
    "gui'": "he she it",
    "hao": "you",
    "gaigue": "present  here",
    "tiempo": "weather  time" ,
    "pa'go": "now  today",
    "yanggen": "if  when (usually connects phrases)",
    "este": "this",
    "esta": "okay  already  see you later" ,
    "hit": "we" ,
    "bumasta": "delay  interrupt" ,
    "pega": "place  put",
    "maskeseha": "even though" ,
    "sintusan": "religious" ,
    "guinaiya": "love",
    "cha'mu": "do not" ,
    "pula'/pupula": "take off/take out",
    "konne'": "catch  take" ,
    "fanhasso": "think  remember" ,
    "enao": "that" ,
    "siña": "can" ,
    "kao": "means it's a question/ question marker",
    "masea": "any either" ,
    "dandan": "play music" ,
    "guinifi": "dream" ,
    "guini": "here" ,
    "kapiya": "chapel  shrine" ,
    "anai": "when" ,
    "guihi": "there" ,
    "guaha": "have  there is  there exists" ,
    "kantora": "singer" ,
    "pale'": "priest" ,
    "ma": "prefix usually with verbs",
    "kañada": "valley" ,
    "sanhiyong": "outside" ,
    "gumando": "play",
    "ya": "like",
    "para": "to (a place)",
    "homanao": "go (to a place)" ,
    "tasi": "beach" ,
    "manaitai": "to read" ,
    "para manu hao": "where are you going" ,
    "hafa tatatmanuhao": "how are you" ,
    "haya": "east" ,
    "lagu": "west" ,
    "luchan": "south" ,
    "kattan": "north",
    "atmoñu": "organ (instrument)",
    "hula": "vow (wedding)",
    "håyi": "who" ,
    "håfa": "what" ,
    "gi månu": "where at" ,
    "sa håfa": "why" ,
    "tai manu": "how" ,
    "simiyas": "seed",
    "chåguan": "grass",
    "odut": "ants",
    "lalangita": "lemon",
    "talanga": "ear",
    "sumi": "leak",
    "tenaki": "rust",
    "nai": "where (relative to thing)/ used in questions with manu and ngai'an",
    "na'i": "give",
    "na'hasso": "cause to think/ remind",
    "nahong/basta": "enough",
    "tiningo'": "know",
    "ñiha": "suffix to express third person/ plural possevive noun their",
    "boka": "eat",
    "hålom": "inside/in",
    "hålom tånu'": "jungle",
    "mulananan": "snore",
    "otro": "other/another",
    "simana": "week",
    "mes": "month",
    "sakkan": "year",
    "otdot": "ant",
    "kuentos": "talk"
}

/**
 * @type {string[]}
 */
export const answers = [

]
const iterator = Object.values(qList)
for (const key of iterator) {
    answers.push(key)
}

export const questionsList = Object.entries(qList);

export const definitionsList = ["sad", "sick", "eat", "everyday", "school", "wife", "girlfriend", "boyfriend", "window", "live (place)", "born", "ask", "at", "he she it", "you", "present here", "weather time", "now today", "if when (usually connects phrases)", "this", "okay already see you later", "we", "delay interrupt", "place put", "even though", "religious", "love", "do not", "take off/take out", "catch take", "think remember", "that", "can", "means it's a question/ question marker", "any either", "play music", "dream", "here", "chapel shrine", "when", "there", "have there is there exists", "singer", "priest", "prefix usually with verbs", "valley", "outside", "play", "like", "to (a place)", "go (to a place)", "beach", "to read", "where are you going", "how are you", "east", "west", "south", "north", "organ (instrument)", "vow (wedding)", "who", "what", "where at", "why", "how", "seed", "grass", "ants", "lemon", "ear", "leak", "rust", "where (relative to thing)/ used in questions with manu and ngai'an", "give", "cause to think/ remind", "enough", "know", "suffix to express third person/ plural possevive noun their", "eat", "inside/in", "jungle", "snore", "other/another", "week", "month", "year", "ant", "talk"]
